# Generated by Django 3.1.1 on 2020-09-18 01:09

from django.db import migrations, models
import filemanager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=filemanager.models.upload_to)),
            ],
        ),
    ]
