# Generated by Django 3.1.1 on 2020-09-18 15:42

import django.core.files.storage
from django.db import migrations, models
import filemanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/Volumes/main_pool'), upload_to=filemanager.models.upload_to),
        ),
    ]
